name: microservice

extensions:
- name: dapr
  components-path: #not sure what goes here yet

services:
- name: yarp-pizza
  project: yarp-pizza\yarp-pizza.csproj
- name: specials-api
  project: specials-api\specials-api.csproj
  replicas: 2
- name: toppings-api
  project: toppings-api\toppings-api.csproj
- name: pizza-app
  project: pizza-app\pizza-app.csproj
- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: "${host}:${port}" 
- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"
- name: mongo
  image: mongo
  bindings:
  - port: 27017
    connectionString: "mongodb://${host}:${port}"